import 'dart:ui';

import 'package:authentication_repository/authentication_repository.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:borrowing/bloc/bloc.dart';
import 'package:formz/formz.dart';
import 'package:shimmer/shimmer.dart';
import '../view_models/view_models.dart';
import 'package:borrowing/models/models.dart';
import 'package:intl/intl.dart';

part 'components/recent.dart';
part 'components/hamburger.dart';
part 'components/date_input.dart';
part 'components/teacher_in_charge_input.dart';
part 'components/forgot_password_form.dart';
part 'components/login_form.dart';
part 'components/borrow_form.dart';
part 'components/regis_form.dart';
part 'components/navbar.dart';
part 'components/loading_indicator.dart';
part 'pages/login.dart';
part 'pages/borrow.dart';
part 'pages/register.dart';
part 'pages/splash.dart';
part 'pages/home.dart';
part 'pages/forgot_password.dart';
part 'pages/history_request.dart';
